# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0003_auto_20160215_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='value',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
