# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0004_auto_20160215_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorhistory',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.Sensor'),
            preserve_default=False,
        ),
    ]
