# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0005_sensorhistory_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorhistory',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainframe.Node'),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainframe.SensorType'),
        ),
    ]
