# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0006_auto_20160215_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
