# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0007_lamp_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='dimmable',
            field=models.BooleanField(default=False),
        ),
    ]
