# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0008_lamp_dimmable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sid',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('node', 'pin', 'sid')]),
        ),
    ]
