# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0009_auto_20160413_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sid',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
