# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0010_auto_20160413_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorhistory',
            name='sid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='value',
            field=models.FloatField(default=None, null=True),
        ),
    ]
