# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-16 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainframe', '0014_sensortype_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sensortype',
            unique_together=set([('name', 'owner')]),
        ),
    ]
