# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0016_node_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_answer_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last answer time'),
        ),
    ]
