# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0017_auto_20160616_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last value time'),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Value at time'),
        ),
    ]
