# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0018_auto_20160616_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='available',
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
