# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0020_usermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='user',
        ),
        migrations.AddField(
            model_name='node',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserMeta',
        ),
    ]
