# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-06-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0021_auto_20160617_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
