# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-03 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0022_auto_20160617_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorhistory',
            options={'ordering': ('time',)},
        ),
        migrations.AlterField(
            model_name='node',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Value at time'),
        ),
        migrations.AlterIndexTogether(
            name='sensorhistory',
            index_together=set([('sensor', 'time')]),
        ),
    ]
