# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0023_auto_20160803_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lamp',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='lamp',
            name='external_id',
            field=models.CharField(db_index=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='external_id',
            field=models.CharField(db_index=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='external_id',
            field=models.CharField(db_index=True, max_length=31, null=True),
        ),
    ]
