# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-16 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0024_auto_20160816_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='auto',
            field=models.NullBooleanField(default=None),
        ),
    ]
