# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-16 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0025_lamp_auto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lamp',
            unique_together=set([('node', 'external_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set([('node', 'external_id')]),
        ),
    ]
