# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0026_auto_20160816_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamp',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='node',
            name='host',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='sensorhistory',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='sensorhistory',
            name='sid',
        ),
        migrations.AddField(
            model_name='node',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
