# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160614132808 on 2016-08-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0027_auto_20160818_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pinging',
            field=models.BooleanField(default=False),
        ),
    ]
