# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.NullBooleanField(default=None)),
                ('pin', models.IntegerField(default=None)),
                ('node', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('node', 'pin'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together=set([('node', 'pin')]),
        ),
    ]
