# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='dimmable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
